export const MESSAGES = {
  REGISTER_SUCCESS: 'REGISTER SUCCESS',
  LOGIN_SUCCESS: 'LOGIN SUCCESS',
  VERIFY_SUCCESS: 'VERIFY SUCCESS',
  LOGOUT_SUCCESS: 'LOGOUT SUCCESS',
  FETCH_SUCCESS: 'FETCH SUCCESS',
  UPDATE_SUCCESS: 'UPDATE SUCCESS',
  DELETE_SUCCESS: 'DELETE SUCCESS',
  VALIDATION_ERROR: 'VALIDATION ERROR',
  SERVER_ERROR: 'SERVER ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT FOUND',
}
